### ISSUE TITLE
Validate and sanitize domain names upon initialization

### ISSUE THREAD

**Issue by kellysutton** [imgix/imgix-php#10]
One of our customers ran into an issue where they accidentally provided a path component to a domain name when initializing an `Imgix\UrlBuilder`.

We should validate and sanitize these, failing as early as possible if necessary.

**Comment by shakaran** [comment]
@kellysutton any progress with this?

A suggestion to validate domains could be use the dns A record to validate if exists:

```
if(!checkdnsrr($exampleDomain, 'A'))
{
    throw new Exception('Not valid domain');
}
```

**Comment by kellysutton** [comment]
Hi @shakaran,

Unfortunately, I no longer work at imgix. You'll need to coordinate with someone there to get this fixed and landed. Best of luck!

**Comment by shakaran** [comment]
Oh sorry @kellysutton for disturb ;) Do you know some useful email or ex-fellow email to contact directly? Thanks.

I will try ping to the contributors, maybe it is some of them
@paulstraw @jacktasia @bjora857 @seanislegend @snowtigersoft @BenMorel

**Comment by kellysutton** [comment]
Try dropping an email to their support address: support@imgix.com
