### ISSUE TITLE
Git ignore or permissions issue

### ISSUE THREAD

**Issue by pretty** [imgix/imgix-php#14]
Hi Guys,

I'm having the most bizarre issue. I added this package using Composer and it just simply wont appear in my Git staged files. In other words I can't commit the package even though it's there on my local machine to my Git repo for deployment.

Any ideas?

I've tried removing and adding again.

/Stefan

**Comment by paulstraw** [comment]
@pretty I'm not sure what would be causing this in the plugin itself… Can you post your `.gitignore`, just for fun?

**Comment by paulstraw** [comment]
Hey @pretty, I'm going to close this due to inactivity, but feel free to reopen if you're still having this issue!
