### ISSUE TITLE
Allow 0 (zero) as value for param

### ISSUE THREAD

**Issue by chredd** [imgix/imgix-php#15]
Hello! 

Right now it is not possible to set a param to a value of zero. It just doesn't show up on the generated URL.

There are some scenarios where you would like to set a param to 0 (zero). One example being: 
* Using a watermark (mark=url) and setting padding to nothing (markpad=0): https://docs.imgix.com/apis/url/watermark/markpad

**Comment by paulstraw** [comment]
Hey @chredd, thanks for the report. I just added [a test](https://github.com/imgix/imgix-php/blob/master/tests/Imgix/Tests/UrlBuilderTest.php#L80) that confirms this is working as expected. Could you send through some example code so I can see what might be happening on your end?

**Comment by chredd** [comment]
Hey @paulstraw!

It turns out I am an idiot. You are absolutely right; it is working just as expected and the problem we had was a bug in our part of the code, that was using your library. 

Sorry for being so fast at pointing the finger at the Imgix lib!

Thanks for the quick response!

Best regards
Chris

**Comment by paulstraw** [comment]
No problem at all. Anything that makes me write more tests is a win, imo!
