### ISSUE TITLE
Add option to exclude library param

### ISSUE THREAD

**Issue by nicoqh** [imgix/imgix-php#17]
Could we add a setter for the `$includeLibraryParam` as well?

Either `public function excludeLibraryParam()` which sets `$includeLibraryParam` to false, or `public function setIncludeLibraryParam($includeLibraryParam)`.

Right now, the constructor gets quite long and unreadable if you want to exclude the library parameter:

```php
$builder = new UrlBuilder("example.imgix.net", true, "1234", null, false);
```

I wanted to discuss the addition first, but I'm happy to make a pull request.

**Comment by thomasjsn** [comment]
@nicoqh I've made one already actually; #16.

**Comment by nicoqh** [comment]
Sorry I missed that! Great :)

I'll close this, then.

**Comment by bryanbuchanan** [comment]
Nothing ever happened with this, did it?

**Comment by davidrapson** [comment]
For anyone who finds this issue in future this has now been added: https://github.com/imgix/imgix-php/pull/32
