### ISSUE TITLE
Umlaut & signed URLs not working

### ISSUE THREAD

**Issue by rubas** [imgix/imgix-php#30]
Every time there is an umlaut in the path, the created secret doesn't match and the Imgix will not show the image.

### Not working
```
$path = '/files/2013/11/Daniel_Müller-Jan.jpg';

$builder = new UrlBuilder(IMGIX_DOMAIN);
$builder->setUseHttps(true);
$builder->setSignKey(IMGIX_SECRET);
$builder->createURL($path, $params);
```

```
$path = '/files/2013/11/Daniel_Müller-Jan.jpg';

$builder = new UrlBuilder(IMGIX_DOMAIN);
$builder->setUseHttps(true);
$builder->setSignKey(IMGIX_SECRET);
$builder->createURL($path, $params, true);
```

### Workaround
`(raw)urlencode` the path.

```
$path = rawurlencode('/files/2013/11/Daniel_Müller-Jan.jpg');

$builder = new UrlBuilder(IMGIX_DOMAIN);
$builder->setUseHttps(true);
$builder->setSignKey(IMGIX_SECRET);
$builder->createURL($path, $params);
```

**Comment by jayeb** [comment]
@rubas I'm a little bit confused--you appear to be using `rawurlencode()` in both examples you've provided here. You're saying the top version doesn't work even though you're raw-encoding the `$path` variable on line 6?

Also, which version of the library are you using? As of [version 1.2.1](https://github.com/imgix/imgix-php/releases/tag/1.2.1), if you pass `true` in as the third argument for the `createURL()` function, the given path will automatically be passed through `rawurlencode()`. You can see the implementation in [PR #27](https://github.com/imgix/imgix-php/pull/27/files). Does this solve your issue?

**Comment by rubas** [comment]
@jayeb sorry for the copy/paste typo in the example. I corrected them above.

It doesn't work if I don't manually encode the path before handing it over. 

The PR #27 parameter is not helping as it seems it is only applied if [the path starts with http](https://github.com/imgix/imgix-php/blob/master/src/Imgix/UrlHelper.php#L25)?!

**Comment by jayeb** [comment]
Ahh okay, I think I understand the issue now. The logic behind when and how to encode paths in our libraries isn't as straightforward as it seems it should be, and we're clearly not doing it correctly in all of our libraries. The correct logic is:

- All paths are expected to be passed in *unencoded*
- If the path matches `/^https?:\/\//`, it should be *fully encoded*, slashes and all (this is for [web proxy](https://docs.imgix.com/setup/creating-sources/web-proxy) sources, where the image path is actually a fully-qualified URL). From my research (my PHP-knowledge is a bit rusty), it seems like `rawurlencode()` is *always* preferred to `urlencode()`.
- If the path does not match `/^https?:\/\//`, it should be *semi-encoded*--encode illegal URL characters, leave everything else alone. There doesn't seem to be a native PHP function to handle this, so we'll need to do some jiggery-pokery to make this work.

I'm gonna put together a PR to iron this out once and for all--stay tuned.

**Comment by rubas** [comment]
`rawurlencode` should be used as it follows [RFC 3986](https://stackoverflow.com/a/996161).

The problem is (as I understand it), that you are using the unencoded path to create the signature but the browser is handling those Umlaut automatically in background and calls Imgix with an encoded path. This means that the generated signature will not match.

Why are you not always encoding the path? Just make sure that `/` and maybe `:` is not encoded. (Either split with those delimeter or replace `%2F` and `%3A`afterwards).

**Comment by sherwinski** [comment]
After some testing on the latest library version, I can confirm that this is no longer an issue. Please feel free to comment back if, for whatever reason, this is still not the case.
