### ISSUE TITLE
Drupal 7 with Imgix

### ISSUE THREAD

**Issue by Nisarg1792** [imgix/imgix-php#33]
I want to implement Imgix module in Drupal 7.  I am working through FTP.  Can anyone implemented in Drupal has better idea.
Thank You!

**Comment by jayeb** [comment]
We don't have any official Drupal support, but you should be able to get things wired up correctly with a bit of effort.

If you have SSL access to your server, we recommend using [Composer](https://getcomposer.org/) to install `imgix-php`. Here's an article on Drupal's website that covers how to install modules via Composer: https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies

If all you have access to is FTP, I'd suggest placing imgix-php in the `/sites/all/modules` folder, alongside other non-core modules you've installed.

Hope this is helpful!

As a side-note, we prefer to use our projects' GitHub ticketing systems for bug reports, feature requests, and other issues directly related to the development of the project. If you have further questions about installation or configuration we'd prefer you reach out through our support desk by emailing support@imgix.com. Thanks!

**Comment by Nisarg1792** [comment]
@jayeb Thank You! Really appreciated.
