### ISSUE TITLE
Dependency http_build_url

### ISSUE THREAD

**Issue by dylanvalade** [imgix/imgix-php#8]
I needed to add PHP support for http_build_url().  This might not be an issue for anyone else but it took me a while to track down and solve.  Used this:
https://github.com/jakeasmith/http_build_url/blob/master/src/http_build_url.php

**Comment by seanislegend** [comment]
+1 same. I would suggest there should be a note on this within the README at the very least.

**Comment by kellysutton** [comment]
Noted. Which versions of PHP are you running?

**Comment by seanislegend** [comment]
I went with the Standalone installation. PHP version 5.3.x.

**Comment by dylanvalade** [comment]
PHP 5.4.23

**Comment by kellysutton** [comment]
Got it. I'll update the README to add a note to include `http_build_url` if it's not available in your environment in the Standalone section.
