### ISSUE TITLE
h-parameter scaling in createSrcSet

### ISSUE THREAD

**Issue by watermusic** [imgix/imgix-php#85]
When i pass height (h) and width (w) parameter to `createSrcSet` function then the width is taken into account in the sourceSet but the height is not adjusted, as is the case in the imgix.js library.

https://github.com/imgix/imgix.js/blob/main/src/ImgixTag.js#L161

**To Reproduce**
Call `createSrcSet` with the parameter `['w' => 1000, 'h' => 500]`. 

The current result looks like this:
```
image.jpg?h=500&w=100 100w
image.jpg?h=500&w=116 116w
image.jpg?h=500&w=134 134w
image.jpg?h=500&w=156 156w
.
.
.
```

**Expected behavior**
The expected result should look like this:
```
image.jpg?h=50&w=100 100w
image.jpg?h=58&w=116 116w
image.jpg?h=67&w=134 134w
image.jpg?h=78&w=156 156w
.
.
.
```

**Information:**
 - imgix-php version: [latest 3.3.1]

**Additional context**
Especially when working with focalPoints, it is important to specify the width together with the height. It is then not enough to pass only the width.

**Comment by sherwinski** [comment]
Hey @watermusic and thanks for opening this issue.

The steps that you provided actually yield a different result for me when run on version 3.3.1:

```php
$ub = new URLBuilder("sherwinski.imgix.net", false, "", false);
$params = array("w" => 1000, "h" => 500);
print($ub->createSrcSet("cat.jpeg", $params));

# http://sherwinski.imgix.net/cat.jpeg?dpr=1&h=500&q=75&w=1000 1x,
# http://sherwinski.imgix.net/cat.jpeg?dpr=2&h=500&q=50&w=1000 2x,
# http://sherwinski.imgix.net/cat.jpeg?dpr=3&h=500&q=35&w=1000 3x,
# http://sherwinski.imgix.net/cat.jpeg?dpr=4&h=500&q=23&w=1000 4x,
# http://sherwinski.imgix.net/cat.jpeg?dpr=5&h=500&q=20&w=1000 5x
```

The [current behavior](https://github.com/imgix/imgix-php#fixed-width-images) of this library is to produce a srcset with pixel density descriptors when `createSrcSet` is called with either a width and/or height parameter passed to it. Based on the test above, it seems to be doing exactly that right now.

Please let me know if there's something I'm missing here or if there are any other questions I can help answer for you.

**Comment by watermusic** [comment]
Please excuse the inaccurate description. In our case, we call the createSrcSet method with its own widths, as tested here. 
https://github.com/imgix/imgix-php/blob/main/tests/Imgix/Tests/UrlBuilderTest.php#L363

But if you add width & height query parameters you get the wrong result.

I have added a test method that describes the error.

```
    public function testCreateSrcSetFromWidthsArrayWithParams() {
        $builder = new UrlBuilder("demos.imgix.net", true, false);
        $opts = array('widths' => array(100, 200, 304, 406, 536));
        $actual = $builder->createSrcSet($path="image.jpg", $params=array('w' => 1000, 'h' => 500), $options=$opts);
        $expected =
'https://demos.imgix.net/image.jpg?h=50&ixlib=php-3.3.1&w=100 100w,
https://demos.imgix.net/image.jpg?h=100&ixlib=php-3.3.1&w=200 200w,
https://demos.imgix.net/image.jpg?h=152&ixlib=php-3.3.1&w=303 304w,
https://demos.imgix.net/image.jpg?h=203&ixlib=php-3.3.1&w=404 406w,
https://demos.imgix.net/image.jpg?h=268&ixlib=php-3.3.1&w=535 536w';

        $this->assertEquals($expected, $actual);
    }
```

But the current result looks like this:

```
'https://demos.imgix.net/image.jpg?h=500&ixlib=php-3.3.1&w=100 100w,
https://demos.imgix.net/image.jpg?h=500&ixlib=php-3.3.1&w=200 200w,
https://demos.imgix.net/image.jpg?h=500&ixlib=php-3.3.1&w=304 304w,
https://demos.imgix.net/image.jpg?h=500&ixlib=php-3.3.1&w=406 406w,
https://demos.imgix.net/image.jpg?h=500&ixlib=php-3.3.1&w=536 536w'
```

But we work with the 'focal point crop' parameter and for that the height is very important.

Example from the imgix Website 
https://gearbox.imgix.net/https%3A%2F%2Fassets.imgix.net%2Funsplash%2Fwalrus.jpg?fp-x=0.12&fp-y=0.56&fp-z=2&fp-debug=true&crop=focalpoint&fit=crop&w=620&h=465&ixlib=js-2.0.0&s=69ce7f1c78d4d945fd3071eab872c995

**Comment by sherwinski** [comment]
@watermusic Thank you for the clarification, I have a much better understanding of your issue now. Let me take this information back to discuss with my team and I will get back to you.

**Comment by sherwinski** [comment]
Hey @watermusic, after giving it some more thought I think there is a different way to achieve the desired effect here.

```php
$builder = new UrlBuilder("demos.imgix.net", true, false);
$opts = array('widths' => array(100, 200, 304, 406, 536));
$actual = $builder->createSrcSet($path="image.jpg", $params=array('ar' => '2:1', 'fit' => 'crop', 'crop' => 'focalpoint', 'fp-x' => 0.12, 'fp-y' => 0.56, 'fp-z' => 2), $options=$opts);
```

Instead of specifying a width and height that maintain aspect ratio, use our [aspect ratio parameter](https://docs.imgix.com/apis/rendering/size/ar) to calculate it on imgix's side for you. Let me know if this solution works for you.

**Comment by watermusic** [comment]
Hey @sherwinski 

Thank you for your quick reply and for your suggestion.

I will have to wait until next week to try the other way.

I will get back to you as soon as possible.
