### ISSUE TITLE
Release a new major version (v4.0) with PHP 8.0+ support only

### ISSUE THREAD

**Issue by adevade** [imgix/imgix-php#95]
With [PHP 7.4 reaching end of life](https://www.php.net/supported-versions.php) in a couple of days, it could be a good opportunity to release a new major version with only PHP 8.0+ support. This would allow for easier contribution without having to worry about older unsupported and insecure versions. `composer.json` currently declares support for [PHP 7.3 and above](https://github.com/imgix/imgix-php/blob/ce9b921f665444265440ec9288701a32a0103d2d/composer.json#L11). And there's a reference to [PHP 7.1 in a code comment](https://github.com/imgix/imgix-php/blob/ce9b921f665444265440ec9288701a32a0103d2d/src/Imgix/UrlBuilder.php#L21).

People stuck on older PHP versions could continue using 3.x until they can upgrade.

I believe that the public APIs should be kept with minimal changes, and could benefit from some type hints, return types and other goodies.

*(Most important of all, replace the hideous `array()`s with `[]` 😅)*

**Comment by sherwinski** [comment]
Hey @adevade and thanks for bringing this to our attention. I definitely agree that this library could benefit from an update and new release. Currently our team is heads down on other work but we will happily review and accept any contributions that help move us toward upgrading. To that end, please fee free to open any PRs or subsequent issues to discuss specific decisions/questions, if needed.

**Comment by adevade** [comment]
I'm happy to help with some PRs, but please read my suggestion in issue #98 about merging breaking changes.

**Comment by adevade** [comment]
Glad to help! 😊

**Comment by adevade** [comment]
Closing because [the v4 release is out](https://github.com/imgix/imgix-php/releases/tag/4.0.0).
