### ISSUE TITLE
Add a coding style, with an automatic formatter

### ISSUE THREAD

**Issue by adevade** [imgix/imgix-php#97]
I think you should add a code formatter to the project, like [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) or [Laravel Pint](https://github.com/laravel/pint) (build on top of PHP-CS-Fixer).

Would make it easier to contribute without having to worry about code style.

**Comment by sherwinski** [comment]
Hey @adevade, agreed that this sounds like a good idea.
We'll look to carve out some time and look into this after the new year. Alternatively, we'd also accept a PR to introduce a formatter into this library if that's something you (or anyone else) is interested in exploring.

**Comment by luqven** [comment]
Addressed by #108 and #104

**Comment by luqven** [comment]
Hey @adevade,

I just wanted to reach out and give you a big shoutout for all your hard work and for giving back to the community. As a token of our appreciation, we'd love to hook you up with some account credit. Please get in touch with support@imgix.com with your account info and send them a link to this comment. They'll get you set up.

We couldn't do it without people like you, and we are grateful for all you do to make imgix-php the best it can be!

**Comment by adevade** [comment]
@luqven Wow, thank you! That's very kind! 😊
