### ISSUE TITLE
Suggestion: Open development branch for accepting PRs to next major version

### ISSUE THREAD

**Issue by adevade** [imgix/imgix-php#98]
To make larger changes I would suggest not merging such PRs directly into `main`, since you have this in the readme: 

```json
{
  "require": {
    "imgix/imgix-php": "dev-main"
  }
}
```

This could mean that people have the main branch running directly in their apps, and that this would break while merging PRs with breaking changes.

**Comment by sherwinski** [comment]
Thanks for the suggestion!

Ideally, most folks are consuming this using composer, but I can see how this could be problematic for those pulling down main into their applications. Maybe the documentation could be better by directing folks to install via composer only to avoid any issues. 

To your first point, I've created a `next` branch which you/others can use to base larger changes off of.
